const mainHeading = document.getElementById('main-heading');
mainHeading.textContent = 'Fruit World';
mainHeading.style.color = 'orange';
const headingEdit = document.getElementById('header');
headingEdit.style.backgroundColor = 'green';
headingEdit.style.borderBottom = '5px solid orange';
const secondHeading = document.getElementById('basket-heading');
secondHeading.style.color = 'green';
const exit = document.getElementById('thanks');
exit.innerHTML = '<p>Please visit us again</p>'